# every push to a branch: run tests
name: Run tests
on:
  workflow_dispatch: {}
#  pull_request:
#    types: [opened, synchronize]
jobs:
  run_tests:
    if: ${{ github.event_name == 'workflow_dispatch' }}  # Only run when manually triggered
    name: Run Nakama tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tests
        run: docker compose -f ./docker-compose-tests.yml up --build --abort-on-container-exit

      - name: Cleanup
        if: always()
        run: docker compose -f ./docker-compose-tests.yml down -v
